### ISSUE TITLE
I cannot deploy because firebase cannot deploy Nuxt lib

### ISSUE THREAD

**Issue by lagmanzaza** [davidroyer/nuxt-ssr-firebase#3]
![screen shot 2561-01-09 at 20 19 19](https://user-images.githubusercontent.com/5283709/34722712-77a4a7f6-f57a-11e7-9a2a-a6eb3c467986.png)

**Comment by ihsanberahim** [comment]
node version issue. firebase only support node 6.* (by the time i reply this)
What we can do is `generate` first then copy the output into the firebase locations.

**Comment by lagmanzaza** [comment]
If I use `generate', I will get prerendered?

**Comment by lagmanzaza** [comment]
Is it not SSR version?

**Comment by ihsanberahim** [comment]
SSR not work as firebase running on node 6 but nuxt require node 9 (by the time i reply this)

**Comment by rolandszpond** [comment]
@lagmanzaza try removing the "^" from the nuxt line in both package.json files since node tries installing the latest version of nuxt instead of 1.0.0-rc11.

On a side note, I've read that firebase functions will only update with latest stable versions (LTS) of node, but the latest is 8.9.4, which nuxt 1.0.0 only requires v8.0.0... hmmm

**Comment by lagmanzaza** [comment]
Oh great  thank you very much, I have a problem I will create new issue
